### ISSUE TITLE
How can I specify cell's height in each cell?

### ISSUE THREAD

**Issue by shiweifu** [splinesoft/SSDataSources#42]
I search the sources, but I didn't found the method in the delegate protocol :

```
- (CGFloat)   tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath
```

so how can I specify the height of cell?

**Comment by shiweifu** [comment]
Oh, I see the comment in `SSSection.h`, I didn't understood before.

**Comment by jhersh** [comment]
@shiweifu `-tableView:heightForRowAtIndexPath:` is part of `UITableViewDelegate`, **not** `UITableViewDataSource`, so SSDataSources does not provide an implementation.

Those properties on `SSSection` are just a convenience; you can cache some numbers there. Your controller (or whatever) should continue to implement `UITableViewDelegate` and can refer to those properties if you find it helpful. Consider something like this:

```objc
- (CGFloat)tableView:(UITableView *)tv heightForRowAtIndexPath:(NSIndexPath *)indexPath {
    NSString *wizard = [self.wizardDataSource itemAtIndexPath:indexPath];

    // calculate and return a height for `wizard`
}
```
