### ISSUE TITLE
Add indexPathForItem or indexForItem to SSSection

### ISSUE THREAD

**Issue by gfzabarino** [splinesoft/SSDataSources#43]
It would be useful to return an index path or index for a given item contained in a SSSection. This would make it easy to check for the inclusion of a given item into an existing SSSection. Right now we have itemAtIndex, bot not indexPathForItem or indexForItem.

**Comment by jhersh** [comment]
@gfzabarino You could do `[mySection.items indexOfObject:anObject]` on your `SSSection`. We could also think about adding a search method to the sectioned data source that searches all sections for an item.

**Comment by gfzabarino** [comment]
You're right I just started with the framework and didn't saw the direct access to the sections backing array. Your suggestion about adding a method to the sectioned data source that would search an item across all sections sounds useful. Feel free to close this issue. Thanks for this framework makes my code so much cleaner and easy to read!

**Comment by jhersh** [comment]
@gfzabarino You may enjoy #45!
