### ISSUE TITLE
Add functionality to remove sections by identifier

### ISSUE THREAD

**Issue by gfzabarino** [splinesoft/SSDataSources#44]
Right now we have to call:

    [self.dataSource removeSectionAtIndex:[self.dataSource indexOfSectionWithIdentifier:SSSomeSectionIdentifier]];

to remove a given section. Something like

    [self.dataSource removeSectionWithIdentifier:SSSomeSectionIdentifier];

would be better. Awesome framework btw, thanks for creating it.

**Comment by segiddins** [comment]
@gfzabarino why don't you make a pull request implementing that?

**Comment by jhersh** [comment]
'cause he's too slow!

**Comment by gfzabarino** [comment]
@segiddins Sure I can do that. LOL just read your comment @jhersh. Sorry, I do am too slow, I'm converting a mess of UITableViewDataSource conforming view controller to use SSDataSources. Thx for that @jhersh!
