### ISSUE TITLE
Missing files in the example project

### ISSUE THREAD

**Issue by koenvanderdrift** [splinesoft/SSDataSources#47]
Hi, I'm trying the example project 'out of the box', and I get a lot of errors regarding missing files :

![screen shot 2015-01-26 at 10 23 04 am](https://cloud.githubusercontent.com/assets/89622/5902065/5db299c6-a545-11e4-9281-03fceac859d2.png)

Where can I find these?

**Comment by jhersh** [comment]
@koenvanderdrift you'll need to run `pod install` in the `Example` folder, then open the generated `.xcworkspace`. Those red file names are not always actually missing; some are generated by CocoaPods at build time.

**Comment by jhersh** [comment]
You can also run `pod try SSDataSources`, which does all the example setup for you.

**Comment by koenvanderdrift** [comment]
Thanks, I also had to install Cocoapods :)

The first command gave me this error:

$ pod install
Analyzing dependencies
Fetching podspec for `SSDataSources` from `../SSDataSources.podspec`
[!] Unable to satisfy the following requirements:

- `OCMock (~> 2.2)` required by `Podfile`
- `OCMock (= 2.2.4)` required by `Podfile.lock`


The second command worked, but then Xcode tells me that OCUnit is deprecated and meeds to be replaced with XCTest.

I'm also getting lots and lots of errors:

![screen shot 2015-01-26 at 11 08 45 am](https://cloud.githubusercontent.com/assets/89622/5902834/e12dfa74-a54b-11e4-893c-221135cda447.png)

**Comment by jhersh** [comment]
That OCMock error is my fault, I'll fix it in a bit. In the meantime, try `pod update` instead.

**Comment by koenvanderdrift** [comment]
Allright, now it works. Thanks!

As a suggestion, maybe you can add these pod commands to a readme?

**Comment by jhersh** [comment]
Done!

**Comment by jhersh** [comment]
Are you still seeing errors in the example project? I don't see them on my end and the sample project does not have `Treat Warnings as Errors` enabled.

**Comment by koenvanderdrift** [comment]
These steps work for me:

1. download and unpack the zip file from the frontpage on github
2. cd to Example folder
3. run `pod update`
4. run 'pod try SSDataSources`
5. close Xcode
6. run `pod install`
7. re-open .xcworkspace

**Comment by jhersh** [comment]
@koenvanderdrift `pod try` clones the repo and runs `pod install` on its own; if you use `pod try` it should not be necessary to do anything else. You don't even need to download any code. :)

Or, you should now be able to clone the repo and follow the instructions now in the readme:

```bash
cd Example
pod install
open ExampleSSDataSources.xcworkspace
```

**Comment by koenvanderdrift** [comment]
I still get this:

Example$ pod install
Analyzing dependencies
Fetching podspec for `SSDataSources` from `../SSDataSources.podspec`
[!] Unable to satisfy the following requirements:

- `OCMock` required by `Podfile`
- `OCMock (= 3.1.2)` required by `Podfile.lock`

**Comment by jhersh** [comment]
Have you cloned the latest master? Also try `pod setup` to set up your local pods cache. Another thing to try would be `pod search OCMock` and make sure you see `3.1.2` as the latest release in the search results.

**Comment by koenvanderdrift** [comment]
No idea why, but `pod search OCMock` kept giving me older versions (causing the error), so I ended up completely removing `cocoapods` and reinstalled it. Everything is working now.

**Comment by jhersh** [comment]
Great! `pod search` only searches your local pods cache. `pod setup` should update the cache and make sure you have the latest specs.
