### ISSUE TITLE
Use of "@import" breaks projects using objective-c++

### ISSUE THREAD

**Issue by sgtsquiggs** [splinesoft/SSDataSources#50]
Modules aren't supported if you are using any obj-c++ code.

Also, "#import" is automatically changed into "@import" at build if modules are enabled.

Why explicitly use @import when you don't have to?

**Comment by jhersh** [comment]
Modern syntax is an end unto itself. :)

But you have a fair point. Perhaps it's worth changing them all back?

**Comment by jhersh** [comment]
Fixed and now available with [`0.8.4`](https://github.com/splinesoft/SSDataSources/releases/tag/0.8.4).
