### ISSUE TITLE
Exception with SSCoreDataSource on iOS 9 - quick fix included

### ISSUE THREAD

**Issue by brunophilipe** [splinesoft/SSDataSources#57]
I had this issue show up for me multiple times when my Core Data objects were changed from views above the associated TableView in the navigation stack:

<img width="1026" alt="screen shot 2015-08-22 at 5 39 22 pm" src="https://cloud.githubusercontent.com/assets/2136642/9425789/381be592-48f5-11e5-8d1c-5e78911bedbb.png">

I figured this happened when the SSCoreDataSource tried to move an object from one indexPath to the same IndexPath while trying to reload it. So I assumed the "move" action was unnecessary and added the following lines:

```objective-c
if (type == NSFetchedResultsChangeMove && [indexPath isEqual:newIndexPath])
		return;
```

to the beginning of the method:

```
- [SSCoreDataSource controller:didChangeObject:atIndexPath:forChangeType:newIndexPath:newIndexPath]
```

It fixes the problem. However I did not open a pull request because this looks very hackish to me. Perhaps there is a better way to prevent it.

Thanks for the great tool! :)

**Comment by jhersh** [comment]
> I figured this happened when the SSCoreDataSource tried to move an object from one indexPath to the same IndexPath while trying to reload it. So I assumed the "move" action was unnecessary and added the following lines:

Are you initiating a move, perhaps by allowing table row reordering, and did you specify a `coreDataMoveRowBlock`? 

The fetched results controller is just reporting the events in your managed object context. Are you changing the models in that context such that a delete and reload occurs for the same index path during the same batch update?

**Comment by brunophilipe** [comment]
I did not set a coreDataMoveRowBlock because in my App the user is not allowed to reorder the items manually. The changes might have triggered a move due to reordering, like when the user changed the value of the entity property used to sort the results in the fetch request.

**Comment by jhersh** [comment]
If you changed multiple fields on an entity such that it was both moved to the top of your fetched objects list AND updated, that might explain the delete/reload behavior. Tricky...maybe best to try and batch changes to your entities, or isolate changes to the field used for sorting.

**Comment by brunophilipe** [comment]
Yes, after careful analysis, I can confirm that the problem is caused by setting two properties of a CoreData object one right after the other.

Basically I have a property `label` and another `hasLabel`, which is used to sort the objects that have a label before the ones that do not. I set the `hasLabel` property from the `didChangeValueForKey()` method inside my managed object.

How would you go by updating multiple properties of a managed object?

**Comment by segiddins** [comment]
@brunophilipe I think doing that inside an observer is likely to cause bugs, since I'm not certain that KVO supports re-entrant calling in a sensible way.

**Comment by brunophilipe** [comment]
So I did some more tests and I am baffled. The fix above worked well on iOS 9, but when running on an iOS 8.4 device (still compiled from Xcode 7 beta), it would result in the same error.
So on a series of trial-and-error tests, I just commented out the ChangeUpdate switch case and everything now works, data is always up to date on the table and no more errors.

```objective-c
        case NSFetchedResultsChangeUpdate:
//            change[@(type)] = indexPath;
//            [tableView reloadRowsAtIndexPaths:@[ indexPath ]
//                             withRowAnimation:self.rowAnimation];
            break;
```

I can only guess this is something broken on Apple's side, despite that not making much sense. I guess this issue is not relevant anymore, so you can close it if you want. Thanks for the support anyway :)
