### ISSUE TITLE
SSCollectionViewController example crash

### ISSUE THREAD

**Issue by huang5556019** [splinesoft/SSDataSources#59]
add "[self.navigationController popViewControllerAnimated:NO];"to SSCollectionViewController in method "- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath"

when Animated set YES will ok;
but Animated set NO will crash

**Comment by segiddins** [comment]
@huang5556019 what leads you to believe that that's a bug in SSDS?

**Comment by huang5556019** [comment]
this crash happen on ios9

**Comment by huang5556019** [comment]
i am not sure,is apple bug or a bug in SSDS

**Comment by huang5556019** [comment]
when you scroll collectionView appeared ,will not crash when Animated set NO

**Comment by huang5556019** [comment]
2015-09-09 11:25:30.402 ExampleSSDataSources[13538:619921] selected item 7597
2015-09-09 11:25:30.408 ExampleSSDataSources[13538:619921] *** Assertion failure in -[UICollectionView _createPreparedSupplementaryViewForElementOfKind:atIndexPath:withLayoutAttributes:applyAttributes:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3505.4/UICollectionView.m:1519

**Comment by huang5556019** [comment]
i only changed blow method in SSCollectionViewController,this crash appeared on xcode7 simulator and ipad catch this crash


- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath {
    NSNumber *item = [self.dataSource itemAtIndexPath:indexPath];
    NSLog(@"selected item %@", item );
    [self.navigationController popViewControllerAnimated:NO];
}

**Comment by segiddins** [comment]
This seems like a bug in your code, rather than SSDS.

**Comment by huang5556019** [comment]
i only add this line "[self.navigationController popViewControllerAnimated:NO]" to example code ;
and test it on ios9 device ,
will go crash
