### ISSUE TITLE
How to disable Index Titles for SSCoreDataSource?

### ISSUE THREAD

**Issue by Ewg777** [splinesoft/SSDataSources#61]
Is there any way to disable it?
Example:
```swift
self.dataSource = SSCoreDataSource(fetchRequest: fetchRequest, inContext: moc, sectionNameKeyPath: "someKey")
```

![example](http://nshipster.s3.amazonaws.com/uilocalizedindexedcollation-example.png)

**Comment by jhersh** [comment]
You could:
- Adjust your data model or fetched results controller to change or remove section titles
- Make a subclass of `SSCoreDataSource`, override `sectionIndexTitlesForTableView:`, and return `nil`

**Comment by Ewg777** [comment]
@jhersh Thanks. Just as I expected
